### ISSUE TITLE
Build Kubernetes Community Day Madrid 2020 Team

### ISSUE THREAD

**Issue by raelga** [kcd-es/madrid-2020#1]
# Kubernetes Community Day Madrid 2020 

## *This event is still in the planning stages. Please check back here for updates!* 

Planning Info available in the [Project Board](https://github.com/orgs/kcd-es/projects/1) - this includes content planning issues!

The event repo is [kcd-es/madrid-2020](https://github.com/kcd-es/madrid-2020).

## What

We'll need to fill the following core roles + shadows to get the ball rolling on strategy and venue selections. Core team will decide on subteam roles (ie - marketing lead will determine if a writer is needed) based on the direction of the event.

This is our first event, so all lead roles are open for self nomination and will be decided in the next public meeting. Shadows do not need to have event experience but should be ok with taking a lead role within the next 12 months of events.

## How

The Guide from the Kubernetes Community Days website:

https://kubernetescommunitydays.org/organizing/

The checklist:

[Kubernetes Community Days Conference Action Items and Assignments
](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=0)

## Team

| Role                                        | Lead | Shadow | Notes |
| ------------------------------------------- | ---- | ------ | ----- |
| Event Lead and Project Management                                |   @raelga   |    @javierprovecho    |       |
| Venue and Registration                                |   @agonzalezro   |    @ereslibre, @serena686, @angelbarrera92 ¿?    |       |
| Sponsorship and partners                                   |  @atsuky     |    @gusraggio, @angelbarrera92 ¿?     |       |
| Content Coordinator                         |   @ereslibre   |    @javierprovecho, @jorgermp     |       |
| Workshops                                   |  @angelbarrera92     |   @javierprovecho      |       |
| Finance                   |  @rgordill    |  @gusraggio      |       |
| Marketing and swag | @gusraggio |  | |
| Accessibility, Inclusiveness, and Diversity | @Malhalma |  @raelga |       |

**Comment by javierprovecho** [comment]
Some suggestions based on my experience contributing to other events:

- Join “Event Lead” with “Project Management”, this would be the first edition, a full time lead won’t be necessary.

- Add “Venue” to “Registration”, as finding a place for the event, find catering options and improving attendees experience (maps, bags, etc).

- Add dedicated role to “Finance”, tracking incomes (sponsors) and expenses (venue, catering, travel support, etc).

- Join “Sponsorship and partners” with “Marketing”, centralizing external communications.

**Comment by andreugallofre** [comment]
As per my experience it may be interesting to have a Design role or someone inside the Marketing team in charge of the design of all stuff needed for the event such as t-shirts/swag (if needed), posters/signs, banners, maps and so.

**Comment by jorgermp** [comment]
If is possible i would like participate as Shadow for Content Coordinator, i have experience in small events and courses.

**Comment by angelbarrera92** [comment]
Ive got experience with workshops and i am interested to be shadow at content coordinator, sponsor and registration.

**Comment by raelga** [comment]
Happy to step up as Event Lead / Project Management role, Content or anything else really. :D

**Comment by raelga** [comment]
## Date

2020, late October.

## Price

Paid entrance, with symbolic price.

## Attendance

About 200, with a max of 300 people.

## Tracks

- Introductory with workshop (optional)
- Advanced

## Weekly meetings

Tuesdays, at 11:00 to 12:00

## Homeworks

Decide lead role to apply and one or two shadow roles to learn.

**Comment by angelbarrera92** [comment]
> Ive got experience with workshops and i am interested to be shadow at content coordinator, sponsor and registration.

I can lead "workshops" and i wanted to be shadow at: "Content Coordinator" and "Sponsorship and partners"

;)

**Comment by ereslibre** [comment]
I can lead "Content Coordinator" and shadow "Event Lead and Project Management" and "Venue and Registration".

**Comment by andreugallofre** [comment]
I can lead "Venue and registration" (But I'm at Barcelona, so I'll need some help at finding a venue) or "Sponsorship and partners" and shadow "Content coordination" and "Finances"

**Comment by gusraggio** [comment]
I can lead or shadow in Marketing and swag and Sponsorship and partners.

**Comment by angelbarrera92** [comment]
As i said via telegram, i will **lead** workshops but i can join as shadow venue or sponsorship.
Let me know!

**Comment by raelga** [comment]
I added myself as shadow for the `Accessibility, Inclusiveness, and Diversity`, but I can lead it if needed.

**Comment by raelga** [comment]
Adding @rgordill as Finances lead and @gusraggio as shadow.

**Comment by raelga** [comment]
The team has been built! 🎉
